---
- name:install_httpd
  hosts: nodes
    tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest
    - name: restart_web
      service:
        name: httpd
        state: running  
...