---
- name: User creation
  hosts: nodes
  vars_files:
    - myvars.yaml
  tasks:
    - name: creation with a list
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ item.pass | password_hash('sha512') }}"
        state: present
        update_password: always
      with_items:
          - { name: "alice", comment: "alice@example.com", pass: "{{ alicepass }}" }
          - { name: "bob", comment: "bob@example.com", pass: "{{ alicepass }}" }
          - { name: "carol", comment: "carol@example.com", pass: "{{ alicepass }}" }